plugins {
    id 'fabric-loom' version '1.7.2'
}

repositories {
    mavenCentral()
    maven { url 'https://maven.fabricmc.net/' }
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:0.16.9"
    // 直接引用本地下载的 meteor-client.jar
    compileOnly files('meteor-client.jar')
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}
